config/routes.rb
Rails.application.routes.draw do
  root to: "books#index"
  devise_for :users
  resources :books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    has_one_attached :pdf_file
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  


  # GET /books
  # GET /books.json
  def index
    #@books = Book.all
    @q = Book.ransack(params[:q])
    @books = @q.result(distinct: true).paginate(page: params[:page], per_page: 5)
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:name, :description, :isbn,:pdf_file)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
 <div class="row">
    <div class="col s12 m7">
      <div class="card">
    
  <div class="card-body">
  <%= form_with(model: book, local: true) do |form| %>
    <% if book.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

        <ul>
        <% book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
  <% end %>

  <div class="form-row">


    <div class="input-field col s6">
      <%= form.label :name %>
      <%= form.text_field :name  %>
    </div>
    

    <div class="input-field col s6">
      <%= form.label :isbn %>
      <%= form.text_field :isbn ,class: 'form-control'%>
    </div>
    <div class="input-field col s12">

      <%= form.label :description %>
      <%= form.text_area :description ,class: 'materialize-textarea' , id: 'textarea2'%>
    </div>
    <div class="input-field col s12">

      <%= form.label :File %>
      <%= form.file_field :pdf_file ,class: 'file-field input-field validate' %>
    </div>


    <div class="input-field col s6">
      <%= form.submit 'Submit ' , class: 'waves-effect waves-light btn-small' %>
    </div>

  </div>
<% end %>

</div>
</div>
</div>
</div>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<div class = "row">
<div class="form-row">
  <div class="input-field col s6">
    <%= search_form_for @q do |f| %>
      <%= f.label :name_or_description_or_isbn_cont %>
      <%= f.search_field :name_or_description_or_isbn_cont ,class: 'form-control' %>

      <%= f.submit "SEARCH" , class: 'waves-effect waves-light btn-small'%>
    <% end %>
  </div>
</div>


<p id="notice"><%= notice %></p>

<div class="table">
<table class="bordered striped centered highlight">
  <thead class="">
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Isbn</th>
      <th >Action</th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td data-label="Name"><%= book.name %></td>
        <td data-label="Description"><%= book.description.first(10) %> ....</td>
        <td data-label="Isbns"><%= book.isbn %></td>
        <td data-label="Action"><%= link_to 'Show', book , class: 'waves-effect waves-light btn-small'%>
        <%= link_to 'Edit', edit_book_path(book) ,class: 'waves-effect waves-light blue btn-small'%>
        <%= link_to 'Destroy', book, method: :delete,class: 'waves-effect waves-light  red btn-small', data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<ul class="pagination">

<%= will_paginate @books %>
</ul>

</div>

<br>

<%= link_to 'New Book', new_book_path , class: 'waves-effect waves-light btn-small'%>

</div>

app/views/books/new.html.erb
<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>


<div class = "row">
   <div class = "col s6">
      <p>
        
        <h2><%= @book.name %></h2>
      </p>
      <p>
        <strong>Description:</strong>
        <%= @book.description %>
      </p>
      <p>
        s<strong>Isbn:</strong>
        <%= @book.isbn %>
      </p>

   </div>
   <div class = "col s12 m12 l12">
    <iframe style=" width:70%; height:500px; " src="https://docs.google.com/gview?url=<%= request.host_with_port + rails_blob_path(@book.pdf_file) %>&embedded=true"></iframe>
 
   </div>
   <div class = "col s12 m12 l12">
    <%= link_to 'Edit', edit_book_path(@book) %> |
    <%= link_to 'Back', books_path %>
   
   </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Material1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <meta name="viewport" content="width=device-width, initial-scale=1.0">

  </head>

  <body>
  
  <nav>
    <div class="nav-wrapper">
      <a href="#!" class="brand-logo center">BOOK-O-PEDIA</a>
      <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
      <ul class="right hide-on-med-and-down">
        <% if user_signed_in? %>
        
            <li> <%= link_to('Logout', destroy_user_session_path, method: :delete) %> </li>
            <li><a href="javascript:void(0)"><%= current_user.email %></a></li>
            
        <% else %>
            <li><%= link_to('Login', new_user_session_path) %>  </li>
            <li><%= link_to('Register', new_user_registration_path) %></li>
        <% end %>
        
        
        
      </ul>
    </div>
  </nav>

  <ul class="sidenav" id="mobile-demo">
    
   
     
     <% if user_signed_in?  %> 
        
        <li> <%= link_to('Logout', destroy_user_session_path, method: :delete) %> </li>
        <li><a href="javascript:void(0)"><%= current_user.email %></a></li>
    <% else %>
        <li><%= link_to('Login', new_user_session_path) %>  </li>
        <li><%= link_to('Register', new_user_registration_path) %></li>
    <% end %>
    
  </ul>
  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>